import {
  Application,
  JSX,
  DefaultTheme,
  DefaultThemeRenderContext,
  PageEvent,
  Reflection,
  Renderer,
  i18n,
} from "typedoc";

/**
 * Custom theme render context for the Fresh theme.
 * Extends the default TypeDoc render context with custom styling and layout.
 */
class FreshRenderContext extends DefaultThemeRenderContext {
  constructor(theme: Fresh, page: PageEvent<Reflection>) {
    super(theme.router, theme, page, theme.application.options);
  }

  // Header: "tsd-page-title" class, breadcrumb and <h1>
  // override header = (props: PageEvent<Reflection>) => <>HEADER</>;

  // Remove footer, just the "Generated by TypeDoc" text
  override footer = () => <></>;

  // Remove settings sidebar. "Member Visibility" filters are not needed, and
  // OS/light/dark theme toggle will be moved to header.
  override settings = () => <></>;

  override toolbar = (props: PageEvent<Reflection>) => {
    return (
      <header class="tsd-page-toolbar">
        <div class="tsd-toolbar-contents container">
          <a
            href={
              this.options.getValue("titleLink") ||
              this.relativeURL("index.html")
            }
            class="title"
          >
            {props.project.name}
          </a>

          <div id="tsd-toolbar-links">
            {Object.entries(this.options.getValue("navigationLinks")).map(
              ([label, url]) => (
                <a href={url}>{label}</a>
              )
            )}
          </div>

          <div class="tsd-theme-toggle">
            {/* <label class="settings-label" for="tsd-theme">
              {i18n.theme_theme()}
            </label> */}
            <select id="tsd-theme">
              <option value="os">{i18n.theme_os()}</option>
              <option value="light">{i18n.theme_light()}</option>
              <option value="dark">{i18n.theme_dark()}</option>
            </select>
          </div>

          <button
            id="tsd-search-trigger"
            class="tsd-widget"
            aria-label={i18n.theme_search()}
            style="
              border: 1px solid var(--color-background-active);
              border-radius: 4px;
            "
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-search-icon lucide-search"
              style="margin-bottom: 1px; margin-left: 4px; margin-right: 8px;"
            >
              <path d="m21 21-4.34-4.34" />
              <circle cx="11" cy="11" r="8" />
            </svg>
            <span style="margin-right: 12ch;">Search…</span>
          </button>
          <dialog id="tsd-search" aria-label={i18n.theme_search()}>
            <input
              role="combobox"
              id="tsd-search-input"
              aria-controls="tsd-search-results"
              aria-autocomplete="list"
              aria-expanded="true"
              spellcheck={false}
              autocapitalize="off"
              autocomplete="off"
              placeholder={i18n.theme_search_placeholder()}
              maxLength={100}
            />

            <ul role="listbox" id="tsd-search-results"></ul>
            <div id="tsd-search-status" aria-live="polite" aria-atomic="true">
              <div>{i18n.theme_preparing_search_index()}</div>
            </div>
          </dialog>
          {/* <a
            href="#"
            class="tsd-widget menu"
            id="tsd-toolbar-menu-trigger"
            data-toggle="menu"
            aria-label={i18n.theme_menu()}
          >
            {this.icons.menu()}
          </a> */}
        </div>
      </header>
    );
  };
}

// TODO: Maybe move this into a separate CSS file and set up a non-tsc bundler.
const styles = `
/* typedoc-theme-fresh */

:root {
  --light-color-background: #fafafe;
  --light-color-background-active: #e6e8ea;
  --light-color-text: #222222;
  --dark-color-background: #18181a;
  --dark-color-background-active: #2d2d2a;
  --dark-color-text: #dfdfd6;
}

@media (prefers-color-scheme: light) {
  ::selection {
    background-color: #11111a20;
  }
}

@media (prefers-color-scheme: dark) {
  ::selection {
    background-color: #bbbbff48;
  }
}

:root[data-theme="light"] {
  ::selection {
    background-color: #11111a20;
  }
}

:root[data-theme="dark"] {
  ::selection {
    background-color: #bbbbff48;
  }
}

.tsd-page-toolbar {
  background-color: transparent;
  border-bottom: none;

  .title {
    font-weight: 500;
    font-size: 18px;
    &:hover {
      color: var(--color-contrast-text);
      text-decoration: none;
    }
  }

  .tsd-theme-toggle {
    display: flex;
    margin-right: 8px;
    
    select {
      border: 1px solid var(--color-background-active);
      border-radius: 4px;
      padding: 6px 4px;
      background: transparent;
      transition: background-color 200ms;
      
      &:hover {
        background-color: var(--color-background-active);
      }
    }
  }
}

.tsd-navigation {
  & > a {
    /* Top-level navigation anchor. */
    margin-block: 16px;
    font-size: 18px;
    background: transparent !important;
    text-decoration: none;
    
    &:hover {
      color: var(--color-contrast-text);
    }
  }

  .tsd-small-nested-navigation {
    margin-left: 8px;
  }
}

.tsd-widget {
  display: flex;
  align-items: center;
  height: auto;
  width: auto;
  padding: 4px;
  font-size: 14px;
  border-radius: 4px;
  transition: background-color 200ms;

  &:hover {
    background-color: var(--color-background-active);
  }
}

#tsd-search-results {
  & > li {
    padding-inline: 6px;
    transition: background-color 200ms;
  }

  a:hover {
    text-decoration: none;
  }
}
`;

/**
 * Fresh theme for TypeDoc.
 *
 * A clean, minimalist and well-designed theme.
 */
export class Fresh extends DefaultTheme {
  constructor(renderer: Renderer) {
    super(renderer);
    renderer.hooks.on("head.end", () => {
      // Insert some extra CSS at the end of the <head> element for this theme.
      return (
        <style type="text/css">
          <JSX.Raw html={styles} />
        </style>
      );
    });

    // Override some of the icons as needed.
    this.icons = {
      ...this.icons,
    };
  }

  override getRenderContext(
    pageEvent: PageEvent<Reflection>
  ): DefaultThemeRenderContext {
    return new FreshRenderContext(this, pageEvent);
  }
}

/**
 * Called by TypeDoc when loading this theme as a plugin.
 */
export function load(app: Application) {
  app.renderer.defineTheme("fresh", Fresh);
}
